"""
Django settings for debirdify project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from ast import literal_eval

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

class MissingEnvVariable(Exception):
    def __init__(self, v, message='Missing environment variable: {}'):
        self.v = v
        self.message = message.format({v})
        super().__init__(self.message)
        
def env(s, default=None):
    if s in os.environ:
        return os.environ[s]
    elif default is not None:
        return default
    else:
        raise MissingEnvVariable(s)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DEBIRDIFY_DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'DEBIRDIFY_DEBUG' in os.environ and os.environ['DEBIRDIFY_DEBUG'].lower() in ('1', 'true')

ALLOWED_HOSTS = set(literal_eval(env('DEBIRDIFY_ALLOWED_HOSTS')))
if DEBUG:
    ALLOWED_HOSTS = ALLOWED_HOSTS.union({'localhost', '127.0.0.1'})
ALLOWED_HOSTS = list(ALLOWED_HOSTS)

TWITTER_CALLBACK_URL = env('DEBIRDIFY_CALLBACK_URL')
TWITTER_CONSUMER_CREDENTIALS = [x.strip() for x in env('DEBIRDIFY_CONSUMER_CREDENTIALS').split(':')]
if len(TWITTER_CONSUMER_CREDENTIALS) != 2:
    raise MissingEnvVariable('DEBIRDIFY_CONSUMER_CREDENTIALS')
TWITTER_CREDENTIALS_COOKIE = env('DEBIRDIFY_ACCESS_CREDENTIALS_COOKIE', 'twitter_access_credentials')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "debirdify.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "libraries": {
                "mid": "templatetags.mid",
            }
        },
    },
]

WSGI_APPLICATION = "debirdify.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
